# Generated by Django 3.2.16 on 2022-11-06 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('questionGenerationApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='numInputs',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
