# Generated by Django 3.2.16 on 2022-11-06 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionGenerationApi', '0002_auto_20221106_1954'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='name',
            field=models.CharField(default='new', max_length=64),
        ),
    ]
