# Generated by Django 3.2.16 on 2022-11-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionGenerationApi', '0003_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(default='unset', help_text='Full answer text'),
        ),
        migrations.AddField(
            model_name='question',
            name='difficulty',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='questionText',
            field=models.TextField(default='unset', help_text='Full question text'),
        ),
    ]
